sudo: required
services:
    - docker

before_install:
    - docker build -t josearivas/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true josearivas/react-test npm run test
    
after_success:
    - docker build -t josearivas/multi-client ./client
    - docker build -t josearivas/multi-nginx ./nginx
    - docker build -t josearivas/multi-server ./server
    - docker build -t josearivas/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those image and push them to docker hub
    - docker push josearivas/multi-client
    - docker push josearivas/multi-nginx
    - docker push josearivas/multi-server
    - docker push josearivas/multi-worker
    
notifications:
    email:
        recipients:
            - rivass.josea@gmail.com
        on_success: always
        on_failure: always

# AWS Elastic Beanstalk
#deploy:
#    provider: elasticbeanstalk
#    region: "us-west-2"
#    app: "docker"
#    env: "Docker-env"
#    bucket-name: "elasticbeanstalk-us-west-2-306476627547"
#    bucker-path: "docker"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#        secure: "$AWS_SECRET_KEY"

# Custom deployment
#deploy:
#    provider: script
#    script: bash scripts/deploy.sh
#    on:
#        branch: master
